### ISSUE TITLE
Default base directory path for logRootDir is not compatible on Linux environment

### ISSUE THREAD

**Issue by surendernz** [Arpit-Shah/Artos#21]
The default configuration in framework_configuration.xml for "logRootDir" is set as ".\reporting\\" which is not compatible in Linux environment.

The same issue applies to all other default file paths set in the configuration (for example 
emailAuthSettingsFilePath = .\conf\user_auth_settings.xml)

**Comment by Arpit-Shah** [comment]
This is caused because of the following: File.separator generates OS-specific path. When Windows detected "\" is used which is not compatible with Linux. If any user constructs a project in Windows and deploys it in Linux then they will face this. The solution should be scoped for release 0.0.17

**Comment by Arpit-Shah** [comment]
Fixed in 0.0.17-beta-1
Solution : Process all path read from a file using `Paths.get().toString() ` . This will remove OS dependency and the path will be regenerated based on OS the test system is running under.
