### ISSUE TITLE
Enhnacement : Add GuardEqualsIgnoreCase(String ref , String actual) in Guard.class

### ISSUE THREAD

**Issue by uditpatel014** [Arpit-Shah/Artos#29]
@Arpit-Shah enhancement aims at checking correctness of two strings ignoring the Upper and Lower cases

**Comment by Arpit-Shah** [comment]
Hello @uditpatel014 , Can you elaborate on your ticket? It does not explain what issue you are facing or any examples of it.

**Comment by uditpatel014** [comment]
Hi @Arpit-Shah ,
Yes, your understanding is correct I am looking to add a guard method to evaluate string values ignoring the cases(Upper and Lower) of the string. I will try to add a method and send a pull request. Thanks

**Comment by uditpatel014** [comment]
Added method for case sensitive string data
