### ISSUE TITLE
MAVEN UPDATE: Publish latest version to maven repository

### ISSUE THREAD

**Issue by UPAT862** [Arpit-Shah/Artos#31]
Hi @Arpit-Shah ,

Can we push the latest ARTOS jar to maven repo. We would like to use it as maven dependency currently using it as local dependency to a jar.

Thanks

**Comment by Arpit-Shah** [comment]
0.0.18 revision is published now

**Comment by Arpit-Shah** [comment]
0.0.18 has been published now
